# Numpy
- based on https://github.com/mephistopheies/mlworkshop39_042017/blob/master/0_python_intro/%D0%A3%D0%BF%D1%80%D0%B0%D0%B6%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F.ipynb

<img src="trainings1.jpg" />

## Task 0
- import numpy

In [2]:
import numpy as np

## Task 1
- print version of numpy

In [3]:
np.version.version

'1.18.1'

## Task 2
- create 1d vector of zeros of size 10

In [4]:
   np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Task 3
- create 1d vector filled with ones of size 10

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Task 4
- create 1d vector filled with ones of size 10,

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Task 5
- crete 1d vector filled with numbers from 10 to 49

In [7]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## Task 6
- create any 1d vector, then reverce it, such that last element will be on the first position

In [8]:
np.arange(10,50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Task 7
- create 2d 3x3 array / matrix, filled with numbers from 0 to 8

In [9]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Task 8
- create 3x3 matrix filled with ones

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Task 9
- create 3x3 matrix filled with random numbers

In [12]:
np.random.rand(3,3)

array([[0.4896905 , 0.32037491, 0.76020375],
       [0.16256495, 0.54140132, 0.64102075],
       [0.62528812, 0.55775813, 0.2569083 ]])

## Task 10
- create 3x3x3 array filled with random numbers

In [13]:
np.random.rand(3,3,3)

array([[[0.9071562 , 0.99544536, 0.30517622],
        [0.97079701, 0.14331597, 0.18848977],
        [0.53228456, 0.36552605, 0.31475286]],

       [[0.04183468, 0.51695134, 0.28993199],
        [0.48099056, 0.54909471, 0.84966357],
        [0.32639345, 0.43877641, 0.43931863]],

       [[0.95885169, 0.80004679, 0.06297915],
        [0.33955363, 0.03948631, 0.68568667],
        [0.78442444, 0.03223015, 0.26066125]]])

## Task 11
- create 10x10 matrix filled with random numbers and find minimal and maximal elements

In [39]:
np.min(np.random.randint(100,size=(10,10)))

2

In [45]:
np.max(np.random.randint(100,size=(10,10)))

98

## Task 12
- create a random 1d vector of size 30 and find average of them

In [48]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

## Task 13
- create 5x5 matrix, which has ones on a "frame" and zeros inside

In [55]:
arr1 = np.ones((5,5))
print(arr1)
arr2 = np.zeros((3,3))
print(arr2)
arr1[1:-1,1:-1] = arr2
print(arr1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Task 14
- create 8x8 matrix
- fill it with ones and zeros in a "chess" order
- **don't use** `tile` funtion

In [8]:
a =np.ones((8,8))
a[::2,1::2]=0
a[1::2,::2]=0
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

## Task 15
- create 8x8 matrix
- fill it with ones and zeros in a "chess" order
- **use** `tile` funtion

In [68]:
a = [[1,0],[0,1]]
np.tile(a,(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

## Task 16
- create two random matrices 5x3 and 3x2
- multiply them

In [76]:
a1 = np.random.randint(0,100,size=(5,3))
a2 = np.random.randint(0,100,size=(3,2))
a3 = np.matmul(a1,a2)

print('a1 =',a1)
print('a2 =',a2)
print('a3 =',a3)

a1 = [[49 58 13]
 [77 36 34]
 [84 92  2]
 [28  1  9]
 [60 78 70]]
a2 = [[46 63]
 [87 15]
 [95 31]]
a3 = [[ 8535  4360]
 [ 9904  6445]
 [12058  6734]
 [ 2230  2058]
 [16196  7120]]


## Task 17
- create array of size 100 filled with random numbers from 0 to 10
- chenge sign of all numbers which are in a range between 3 and 8

In [81]:
a1 = np.random.randint(0,10,size=(100))
print(a1)
a1[((a1>=3)&(a1<=8))] = a1[((a1>=3)&(a1<=8))]  * -1
print(a1)

[0 6 3 1 8 2 5 0 6 7 0 9 5 7 1 4 2 2 2 1 5 0 3 1 0 5 0 9 6 1 3 5 4 2 4 3 5
 5 3 9 5 0 9 1 6 6 4 8 4 1 3 3 2 7 0 9 2 4 7 5 5 6 2 9 9 0 6 5 5 0 3 6 8 0
 3 7 8 3 6 8 9 7 1 5 3 3 5 7 5 0 2 3 9 1 0 1 3 5 2 1]
[ 0 -6 -3  1 -8  2 -5  0 -6 -7  0  9 -5 -7  1 -4  2  2  2  1 -5  0 -3  1
  0 -5  0  9 -6  1 -3 -5 -4  2 -4 -3 -5 -5 -3  9 -5  0  9  1 -6 -6 -4 -8
 -4  1 -3 -3  2 -7  0  9  2 -4 -7 -5 -5 -6  2  9  9  0 -6 -5 -5  0 -3 -6
 -8  0 -3 -7 -8 -3 -6 -8  9 -7  1 -5 -3 -3 -5 -7 -5  0  2 -3  9  1  0  1
 -3 -5  2  1]


## Task 18
- create a matrix 5x5 such that each row would be a 1d array filled with numbers from 0 to 4

In [112]:
a = [0,1,2,3,4]
np.vstack([a,a,a,a,a])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

## Task 19
- create 1d vector of size 100 filled with random values from range 0-1, excluding boundary values (no exact 0/1)

In [152]:
np.random.uniform(low=0.1, high=.99, size=(100,))

array([0.91874783, 0.19028375, 0.22285303, 0.44713655, 0.9892861 ,
       0.77975489, 0.9170719 , 0.87766583, 0.60439286, 0.59279877,
       0.12843868, 0.36281415, 0.748593  , 0.89924829, 0.16158864,
       0.21589427, 0.85029587, 0.21175775, 0.70327231, 0.53376531,
       0.36313556, 0.41125324, 0.10237408, 0.21166162, 0.8392854 ,
       0.65184591, 0.35504764, 0.6992582 , 0.51471138, 0.96621981,
       0.78013507, 0.34492366, 0.25955929, 0.26797023, 0.30310006,
       0.9256282 , 0.22594759, 0.17440609, 0.64473467, 0.58134092,
       0.6216081 , 0.588684  , 0.30630897, 0.63266014, 0.75434471,
       0.79593837, 0.21128372, 0.65804672, 0.45664041, 0.60661794,
       0.1247662 , 0.10778823, 0.29600882, 0.75995453, 0.43891069,
       0.34882464, 0.84670047, 0.30651419, 0.55630924, 0.57724022,
       0.12586719, 0.14976261, 0.18469654, 0.49306717, 0.48125977,
       0.65710993, 0.16433878, 0.50877639, 0.78119367, 0.79001717,
       0.6115001 , 0.74201067, 0.95669123, 0.15932425, 0.28342

## Task 20
- create a 10x2 random matrix filled with number from range 0-100
- consider it as points in Cartesian plain
- convert to polar system of coordinates

In [159]:
np.random.randint(0,101,size=(10,2))

array([[45, 19],
       [85, 83],
       [94, 47],
       [81, 99],
       [ 6, 62],
       [25, 38],
       [72, 87],
       [27, 51],
       [41, 58],
       [86, 96]])

## Task 21
- create random 13x13 matrix, replace maximal element to zero

In [168]:
a = np.random.randint(0,100,size=(13,13))
print(a)
print(np.max(a))
a[np.where (a==np.max(a))] = 0
print(a)

[[32  1 96 27 68 42 59 48 86 61 87 56 87]
 [20 31 54 44 14 11 86 76 48 92 30 94 31]
 [50 66 36 80 57 51 55 24 41 46 54 33 27]
 [99 78 53 26 71 98 20 14  7 87 23 51 45]
 [33  5 32 69 27  7 95 11 46 61 40 65 69]
 [ 2 73 30 16 41  6 77  0 12 17 50 74 61]
 [81 78 91 34  2 66 95 39 80 61 64  6 44]
 [72 59 22 40 35 75 23 97 21 93 43 26 94]
 [26 64 17 85 96 14  3 88 79 99 27 78 72]
 [59 31 63 75 43 27 23 38 41 76 20 94 16]
 [24 61 77 31 65 51 56 99 19 69 64 70 27]
 [15 92 15  5 53 34  8 29 51 16 42 79 53]
 [58  8 33 55 34 32 85 25 44 57 82 56 97]]
99
[[32  1 96 27 68 42 59 48 86 61 87 56 87]
 [20 31 54 44 14 11 86 76 48 92 30 94 31]
 [50 66 36 80 57 51 55 24 41 46 54 33 27]
 [ 0 78 53 26 71 98 20 14  7 87 23 51 45]
 [33  5 32 69 27  7 95 11 46 61 40 65 69]
 [ 2 73 30 16 41  6 77  0 12 17 50 74 61]
 [81 78 91 34  2 66 95 39 80 61 64  6 44]
 [72 59 22 40 35 75 23 97 21 93 43 26 94]
 [26 64 17 85 96 14  3 88 79  0 27 78 72]
 [59 31 63 75 43 27 23 38 41 76 20 94 16]
 [24 61 77 31 65 51 56  0 19 6

## Task 22
- create two 1d arrays with random values
- make a Cauchy matrix from them $C (C_{ij} = \frac{1}{x_i - y_j})$

In [29]:
x = np.random.randint(1,10,size=(4))
y = np.array([5,6,7])  
x = x.reshape((-1,1))
diff_matrix = x-y
cauchym = 1.0/diff_matrix
print(cauchym)

[[-0.33333333 -0.25       -0.2       ]
 [-0.25       -0.2        -0.16666667]
 [ 0.33333333  0.5         1.        ]
 [-0.33333333 -0.25       -0.2       ]]


In [283]:
x = np.random.randint(0,10,size=(4))
y = np.random.randint(0,10,size=(3))
x = x.reshape((-1,1))
diff = x - y
cauchym = 1.0/diff
print(x)
print(y)
print(cauchym)

[[1]
 [3]
 [7]
 [0]]
[2 2 6]
[[-1.         -1.         -0.2       ]
 [ 1.          1.         -0.33333333]
 [ 0.2         0.2         1.        ]
 [-0.5        -0.5        -0.16666667]]


## Task 23
- create an array of random `float` numbers and convert it to `int`

In [183]:
a = np.random.random((3,3)) * 10
print(a)
b=a.astype(int)
print(b)

[[5.9805171  5.39041682 1.03701264]
 [5.47426551 0.46945431 9.88414902]
 [6.40164594 0.82019375 6.58133178]]
[[5 5 1]
 [5 0 9]
 [6 0 6]]


## Task 24
- create 1d array of numbers from 0 to 15
- put each of them in random positions inside 4x4 matrix

In [186]:
np.arange(0,16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Task 25
- create random 100x50 matrix
- deduct avarage of each row from correspondatn rows

In [189]:
a = np.random.randint(0,100,size=(100,50))
a.mean(axis=0)

array([50.18, 51.31, 48.07, 51.19, 51.82, 50.01, 46.1 , 51.02, 44.6 ,
       45.57, 53.95, 46.64, 45.7 , 53.27, 52.5 , 51.7 , 47.27, 51.35,
       47.83, 51.2 , 50.07, 49.04, 50.03, 50.22, 51.12, 43.91, 47.77,
       49.33, 50.21, 52.1 , 48.17, 49.34, 50.82, 51.68, 44.62, 51.89,
       44.27, 54.68, 44.59, 48.21, 47.42, 47.42, 50.63, 47.26, 46.  ,
       46.3 , 51.72, 53.95, 51.07, 45.85])

## Task 26 
- create random 10x10 matrix
- extract diagonal elements and put them into 1d array

In [200]:
a = np.random.randint(100,size=(10,10))
b = (np.identity(10) == 1)
print(a)
print(b)
c = a[b]
print(c)

[[59 55 16 81 38 64 84 45 21 40]
 [ 9 68 66  5 68 64 63 31 24 12]
 [89 23 38 50 82 40 68 90 83 16]
 [61 41 46 64 70  5 36 32 60 34]
 [46 40 61  7 33 66 50 20 77 78]
 [33 66  7 69 83 41 79 28  2 12]
 [22 66 56 40 22 28 23  9 37 58]
 [37 62 76 58 84 11 26 19 31 61]
 [42 72 18 94 49  4  9 98 93 61]
 [78 10 24 81 92 19 94 85 84 67]]
[[ True False False False False False False False False False]
 [False  True False False False False False False False False]
 [False False  True False False False False False False False]
 [False False False  True False False False False False False]
 [False False False False  True False False False False False]
 [False False False False False  True False False False False]
 [False False False False False False  True False False False]
 [False False False False False False False  True False False]
 [False False False False False False False False  True False]
 [False False False False False False False False False  True]]
[59 68 38 64 33 41 23 19 93 67]


In [205]:
a = np.random.randint(100,size=(10,10))
b = np.identity(10)
c = a[(a*b > 0)]
print(a)
print(c)

[[40 79 29 55 87 77 95 29 81 21]
 [ 3 22  2 93  4 21 17 79 71 33]
 [71 19 65 29 36 79  2 82  5 79]
 [ 7 45 36  2 37 65 44 76 69 15]
 [72 62 45 27 65 89  9  2 21 93]
 [ 1 88 91  9 45  6 58 47 81 44]
 [38 73 89 62  4  0 46 24 35 85]
 [38 94  7 92 21  9 10 94 33 26]
 [81 31 97 62 14 56 28  5 99 91]
 [34 83 79  0 73 55 56 46 20 12]]
[40 22 65  2 65  6 46 94 99 12]


## Task 27
- given a vector `[1, 2, 3, 4, 5]`
- build a new vertor with three zeros between each element

In [269]:
a = np.array([1, 2, 3, 4, 5])
n=a.shape[0]
m = n + (n-1) * 3
out = np.zeros(m,dtype=a.dtype)
out[::4] = a
out

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])